import type { AlertRecord, EmailRecord } from "./types";

export const mockEmails: EmailRecord[] = [
  {
    id: 1,
    gmailMessageId: "mock-1",
    sender: "recruiting@rbc.com",
    subject: "Interview invitation — Financial Analyst",
    snippet: "We would like to schedule a call to discuss the next steps...",
    receivedAt: "2026-06-07T09:15:00",
    category: "interview_invitation",
    importance: "high",
    requiresAction: true,
    aiUsed: false,
  },
  {
    id: 2,
    gmailMessageId: "mock-2",
    sender: "talent@kpmg.ca",
    subject: "Complete your online assessment",
    snippet: "Please complete the assessment by June 10...",
    receivedAt: "2026-06-06T14:30:00",
    category: "assessment",
    importance: "high",
    requiresAction: true,
    aiUsed: false,
  },
  {
    id: 3,
    gmailMessageId: "mock-3",
    sender: "careers@cgi.com",
    subject: "Thank you for applying",
    snippet: "We received your application for Business Analyst...",
    receivedAt: "2026-06-04T11:00:00",
    category: "application_confirmation",
    importance: "low",
    requiresAction: false,
    aiUsed: false,
  },
  {
    id: 4,
    gmailMessageId: "mock-4",
    sender: "hr@slcmanagement.com",
    subject: "Update on your application",
    snippet: "Unfortunately, we will not be moving forward...",
    receivedAt: "2026-06-03T16:45:00",
    category: "rejection",
    importance: "medium",
    requiresAction: false,
    aiUsed: false,
  },
];

export const mockAlerts: AlertRecord[] = [
  {
    id: 1,
    title: "Interview invitation",
    message: "RBC invited you to interview for Financial Analyst.",
    alertType: "interview_invitation",
    read: false,
    createdAt: "2026-06-07T09:15:00",
  },
  {
    id: 2,
    title: "Assessment due soon",
    message: "KPMG asked you to complete an assessment by June 10.",
    alertType: "assessment",
    read: false,
    createdAt: "2026-06-06T14:30:00",
  },
  {
    id: 3,
    title: "Application update",
    message: "SLC Management has decided not to move forward.",
    alertType: "rejection",
    read: true,
    createdAt: "2026-06-03T16:45:00",
  },
];
