import type { RuleDefinition } from "./types";

export const NON_APPLICATION_SENDER_DOMAINS = [
  "linkedin.com",
  "indeed.com",
  "glassdoor.com",
  "ziprecruiter.com",
  "monster.com",
  "mailchimp.com",
  "google.com",
  "notifications.google.com",
];

export const ATS_SENDER_DOMAINS = [
  "greenhouse.io",
  "lever.co",
  "workday.com",
  "myworkdayjobs.com",
  "icims.com",
  "smartrecruiters.com",
  "ashbyhq.com",
  "jobvite.com",
  "bamboohr.com",
  "ultipro.com",
  "successfactors.com",
  "successfactors.eu",
];

export const CLASSIFICATION_RULES: RuleDefinition[] = [
  {
    category: "offer",
    keywords: [
      "offer",
      "congratulations",
      "pleased to offer",
      "employment agreement",
      "compensation package",
      "offer letter",
    ],
    suggestedStatus: "Offer",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.9,
    priority: 10,
  },
  {
    category: "rejection",
    keywords: [
      "unfortunately",
      "not selected",
      "moving forward with other candidates",
      "will not be proceeding",
      "position has been filled",
      "not moving forward",
      "decided not to move forward",
      "after careful consideration",
      "regret to inform",
      "unable to move forward",
      "other candidates",
      "decided to pursue",
      "will not be moving forward",
      "cannot offer you",
      "we have decided",
      "not able to offer",
      "filled the position",
      "chosen to proceed with other",
    ],
    suggestedStatus: "Rejected",
    importance: "medium",
    requiresAction: false,
    baseConfidence: 0.88,
    priority: 9,
  },
  {
    category: "interview_invitation",
    keywords: [
      "interview",
      "schedule a call",
      "meet with",
      "hiring manager",
      "availability",
      "select a time",
      "calendar invite",
      "phone screen",
      "virtual interview",
      "video interview",
      "interview invitation",
      "invite you to interview",
      "phone interview",
      "onsite interview",
      "panel interview",
    ],
    suggestedStatus: "Interview",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.86,
    priority: 8,
  },
  {
    category: "assessment",
    keywords: [
      "assessment",
      "online assessment",
      "coding challenge",
      "case study",
      "complete by",
      "video interview",
      "one-way interview",
      "take-home",
      "skills test",
      "hacker rank",
      "codility",
    ],
    suggestedStatus: "Assessment",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.84,
    priority: 7,
  },
  {
    category: "deadline",
    keywords: [
      "deadline",
      "due by",
      "due date",
      "respond by",
      "reply by",
      "submit by",
      "expires on",
      "no later than",
    ],
    suggestedStatus: "Assessment",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.8,
    priority: 6,
  },
  {
    category: "recruiter_message",
    keywords: [
      "recruiter",
      "talent acquisition",
      "next steps",
      "follow up",
      "following up",
      "reach out",
      "connect with me",
      "discuss your application",
    ],
    suggestedStatus: "Interview",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.78,
    priority: 5,
  },
  {
    category: "application_confirmation",
    keywords: [
      "thank you for applying",
      "application received",
      "we received your application",
      "your application has been submitted",
      "thanks for your interest",
      "application submitted",
      "successfully applied",
      "received your resume",
      "under review",
      "reviewing your application",
      "shortlisted",
    ],
    suggestedStatus: "Applied",
    importance: "low",
    requiresAction: false,
    baseConfidence: 0.82,
    priority: 4,
  },
  {
    category: "job_alert",
    keywords: [
      "job alert",
      "new jobs",
      "recommended job",
      "jobs matching",
      "job recommendation",
      "new opportunity",
      "similar jobs",
    ],
    suggestedStatus: "Unknown",
    importance: "low",
    requiresAction: false,
    baseConfidence: 0.72,
    priority: 3,
  },
];

export const JOB_DOMAIN_HINTS = [
  "careers",
  "recruiting",
  "talent",
  "jobs",
  "hr",
  "hiring",
];

export const COMPANY_DOMAIN_MAP: Record<string, string> = {
  rbc: "RBC",
  kpmg: "KPMG",
  cgi: "CGI",
  cibc: "CIBC",
  td: "TD Bank",
  slcmanagement: "SLC Management",
  google: "Google",
  siemens: "Siemens",
  tradedesk: "The Trade Desk",
  thetradedesk: "The Trade Desk",
};
