import type { RuleDefinition } from "./types";

export const CLASSIFICATION_RULES: RuleDefinition[] = [
  {
    category: "offer",
    keywords: [
      "offer",
      "congratulations",
      "pleased to offer",
      "employment agreement",
      "compensation package",
      "offer letter",
    ],
    suggestedStatus: "Offer",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.9,
    priority: 10,
  },
  {
    category: "rejection",
    keywords: [
      "unfortunately",
      "not selected",
      "moving forward with other candidates",
      "will not be proceeding",
      "position has been filled",
      "not moving forward",
      "decided not to move forward",
    ],
    suggestedStatus: "Rejected",
    importance: "medium",
    requiresAction: false,
    baseConfidence: 0.88,
    priority: 9,
  },
  {
    category: "interview_invitation",
    keywords: [
      "interview",
      "schedule a call",
      "meet with",
      "hiring manager",
      "availability",
      "select a time",
      "calendar invite",
      "phone screen",
    ],
    suggestedStatus: "Interview",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.86,
    priority: 8,
  },
  {
    category: "assessment",
    keywords: [
      "assessment",
      "online assessment",
      "coding challenge",
      "case study",
      "complete by",
      "video interview",
      "one-way interview",
      "take-home",
      "skills test",
    ],
    suggestedStatus: "Assessment",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.84,
    priority: 7,
  },
  {
    category: "deadline",
    keywords: [
      "deadline",
      "due by",
      "due date",
      "respond by",
      "reply by",
      "submit by",
      "expires on",
      "no later than",
    ],
    suggestedStatus: "Assessment",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.8,
    priority: 6,
  },
  {
    category: "recruiter_message",
    keywords: [
      "recruiter",
      "talent acquisition",
      "next steps",
      "follow up",
      "following up",
      "reach out",
      "connect with me",
      "discuss your application",
    ],
    suggestedStatus: "Interview",
    importance: "high",
    requiresAction: true,
    baseConfidence: 0.78,
    priority: 5,
  },
  {
    category: "application_confirmation",
    keywords: [
      "thank you for applying",
      "application received",
      "we received your application",
      "your application has been submitted",
      "thanks for your interest",
    ],
    suggestedStatus: "Applied",
    importance: "low",
    requiresAction: false,
    baseConfidence: 0.82,
    priority: 4,
  },
  {
    category: "job_alert",
    keywords: [
      "job alert",
      "new jobs",
      "recommended job",
      "jobs matching",
      "job recommendation",
      "new opportunity",
      "similar jobs",
    ],
    suggestedStatus: "Unknown",
    importance: "low",
    requiresAction: false,
    baseConfidence: 0.72,
    priority: 3,
  },
];

export const JOB_DOMAIN_HINTS = [
  "careers",
  "recruiting",
  "talent",
  "jobs",
  "hr",
  "hiring",
];

export const COMPANY_DOMAIN_MAP: Record<string, string> = {
  rbc: "RBC",
  kpmg: "KPMG",
  cgi: "CGI",
  cibc: "CIBC",
  td: "TD Bank",
  slcmanagement: "SLC Management",
  google: "Google",
  microsoft: "Microsoft",
};
